### ISSUE TITLE
how to model some fiellds from GOBL to KSeF FA(2)

### ISSUE THREAD

**Issue by alapierre** [invopop/gobl.ksef#6]
hello, 

I'm working on Java based converter for GOBL to FA(2) and I'm looking for way to map some fields from GOBL:

- `RachunekBankowy/NrRB` - bank account number
-  `RachunekBankowy/NazwaBanku` - name of the bank

I notice `https://gobl.org/draft-0/pay/terms` but I'm not sure. 

Other questions:
 - how about self invoicing `P_17`?
 - `P_16` - "metoda kasowa"
 - `P_18A` - Split payment?

can you provide little bit more complex sample of `invoice.json`? I have reviewed your main project on GitHub (https://github.com/invopop/gobl/tree/main/regimes/pl), but unfortunately, I did not find the answer there either.

**Comment by noplisu** [comment]
Hey @alapierre

GOBL for KSeF is in early stages of development and is not yet production ready. The structure you are looking for in payment details would look something like this:
```json
{
    "$schema": "https://gobl.org/draft-0/envelope",
    ...
    "doc": {
        "$schema": "https://gobl.org/draft-0/bill/invoice",
        ...
        "payment": {
            "instructions": {
                "key": "credit-transfer",
                "credit_transfer": [
                    {
                        "number": "61109010140000071219812874",
                        "name": "PKO BP"
                    }
                ]
            }
        }
    }
}
```
Where number is RachunekBankowy/NrRB and name RachunekBankowy/NazwaBanku

**Comment by noplisu** [comment]
As for the other questions we don't examples for those cases yet. Their implementation will be similar to the one we have in the italian FatturaPA so maybe you can find some answers there: https://github.com/invopop/gobl/blob/main/regimes/it/README.md

**Comment by alapierre** [comment]
thank you, it is not important in that moment, I just looking and plaing with GOBL format.
